### ISSUE TITLE
A new PyPI release?

### ISSUE THREAD

**Issue by coredumperror** [Alir3z4/django-crequest#6]
Could you make a new release for PyPI, please? That encoding error that you fixed 5 months ago is necessary to make this module work in Python 3, which my team needs. 

We're installing the package directly from here for now, but it'd be very nice to be able to install from an official PyPI build.

Thanks!

**Comment by mscout1** [comment]
I would like to second this request. We are updating to python 3 and would like to use this,

**Comment by Alir3z4** [comment]
If we can get a fix for https://github.com/Alir3z4/django-crequest/issues/7 then I'll make a release right away.

**Comment by Alir3z4** [comment]
Latest release is out https://github.com/Alir3z4/django-crequest/releases/tag/2018.5.11
